intrinsic TriangleTheta(Sk::SeqEnum[SeqEnum[RngSerPowElt]], Gamma::GrpPSL2Tri :
                        Al := "ByValues", Recompute := false) -> Any
{}
  if not Recompute and assigned Gamma`TriangleTheta and
      Precision(Parent(Gamma`TriangleTheta)) ge Precision(BaseRing(Parent(Sk[1][1]))) then
    return Gamma`TriangleTheta;
  end if;

  prec := Precision(BaseRing(Parent(Sk[1][1])));
  eps := 10^(-prec/2);

  aut := #AutomorphismGroup(Gamma);
  if aut gt 1 then
    vprintf Shimura : "Gulp, automorphism group size > 1!\n";
  end if;

  if Al eq "Ratio" then
    // First take the one with the smallest stabilizer
    // TODO: Use finer information from automorphism group here (PointedReps?)
    sigma := DefiningPermutation(Gamma);
    _, gap1 := Max([#c : c in CycleDecomposition(sigma[1])]);
    gap1 := 1;   // blarg?
    Sk1 := [f[gap1] : f in Sk];

    // Find the element in the basis with the smallest "gap" between nonzero coefficients
    gaps := [];
    ss := [];
    for f in Sk1 do
      s := Degree(LeadingTerm(f));
      while Abs(Coefficient(f,s)) lt eps do
        s +:= 1;
      end while;
      Append(~ss, s);
      sj := s+1;
      while Abs(Coefficient(f,sj)) lt eps do
        sj +:= 1;
      end while;
      Append(~gaps, sj-s);
    end for;
    mingap, gapind := Min(gaps);
    vprintf Shimura : "Taking gap = %o with index %o\n", mingap, gapind;

    f := Sk1[gapind];
    s := ss[gapind];
    n := s+mingap;

    if mingap gt 1 and Abs(Coefficient(f,n+1)) gt eps then
      s := n;
      n := s+1;
      mingap := 1;
    end if;
    // assert mingap le 2;  // otherwise have to be clever about a root of unity?

    // check if "next" coefficient is nonvanishing, since simpler
    // TODO: Otherwise use weighted scaling. Also, can deal with larger
    // mingap in same way.
    Theta := (Factorial(n-s)*Coefficient(f,n)/Coefficient(f,s))^(1/mingap);
  else // Al eq "ByValues"
    // Normalize so that the sum of the values is 1.
    vals := TriangleRamificationValues(Sk, Gamma : NormalizeByTheta := false);
    CCvals := BaseRing(Parent(Sk[1][1]));
    Thetainvs := &cat[ [ &+[CCvals | vals[s][i][j+1]/vals[s][i][j] : i in [1..#vals[1]] | Abs(vals[s][i][j]) gt eps] : j in [1..#vals[1][1]-1]] : s in [1..3]];
    Thetainvs := [Thetainv : Thetainv in Thetainvs | Abs(Thetainv) gt eps and Abs(Thetainv) lt 1/eps];
    if #Thetainvs eq 0 then
      vprintf Shimura : "Tried Al := 'ByValues' but failed, so now using 'Ratio'\n";
      Theta := TriangleTheta(Sk, Gamma : Al := "Ratio", Recompute := true);
    else
      _, thind := Min([Abs(Abs(Thetainv)-1) : Thetainv in Thetainvs]);  // choose close to 1 in absval
      Theta := Thetainvs[thind]^-1;
    end if;
  end if;

  Gamma`TriangleTheta := Theta;

  vprintf Shimura : "Theta = %o\n", Theta;

  return Theta;
end intrinsic;

/*
intrinsic TriangleMakeNumberField(uCC::FldComElt, deg::RngIntElt : K := "") -> Any
  {Given a complex number uCC thought to be algebraic, return the optimized representation of the number field Kop generated by uCC, along with embedding data consisting of a place of Kop and a boolean for complex conjugation.}

  
  if m eq 1 then
    vprint Shimura : "  ...m eq 1, so taking QQ";
    K := RationalsAsNumberField();
    v := RealPlaces(K)[1];
    return true, K, v, false, Parent(uCC)!1;
  end if;

  vprintf Shimura : "  ...Trying to MakeK with m = %o\n", m;

  CC := Parent(uCC);
  eps := 10^(-Precision(CC)/2);

  u_pol := PowerRelation(uCC, m : Al := "LLL");
  if Degree(u_pol) ne m or not IsIrreducible(u_pol) then
    if Degree(u_pol) gt 1 then
      vprint Shimura : "  ...coefficient not degree m, looked like degree", [<Degree(c[1]),c[2]> : c in Factorization(u_pol)];
    end if;
    return false, _, _, _, _;
  end if;
  lc := LeadingCoefficient(u_pol);
  K0 := NumberField(u_pol);
  u0 := K0.1;
  K := NumberField(MinimalPolynomial(lc*u0));
  u := K.1/lc;
  ps, foobar := TrialDivision(Discriminant(K));
  if foobar ne 1 and not IsSquare(foobar) then
    return false, _, _, _, _;
  end if;

  if foobar eq 1 then
    vprintf Shimura : "  ...coefficient found, with ps = %o and foobar = 1\n", ps;
  else
    vprintf Shimura : "  ...coefficient found, with ps = %o and sqrt(foobar) = %o\n", ps, Round(Sqrt(CC!foobar));
  end if;
  vprintf Shimura : "  ...%o\n", K;
  vprint Shimura : "  ...Trying to optimize"; 
  
  Kop, iotaop := OptimizedRepresentation(K : Ramification := [p[1] : p in ps]);
  uop := iotaop(u);
  
  vprintf Shimura : "  ...successfully optimized\n  Kop = %o\n  now finding complex embedding\n", Kop;
  minv, vind := Min([Abs(uCC-Evaluate(uop,v : Precision := Precision(CC))) : v in InfinitePlaces(Kop)]);
  if minv gt eps then
    // Need complex conjugate
    minv, vind := Min([Abs(Conjugate(uCC)-Evaluate(uop,v : Precision := Precision(CC))) : v in InfinitePlaces(Kop)]);
    conj := true;
  else
    conj := false;
  end if;
  if minv gt eps then
    vprint Shimura : "  ...failed to match; got a polynomial but it apparently sux";
    return false, _, _, _, _;
  end if;
  vprint Shimura : "  ...quality of match", RealField(4)!minv;
  v := InfinitePlaces(Kop)[vind];
  // return true, Kop, v, conj, uop;
  return true, Kop, v, conj, uCC;
end intrinsic;
*/

intrinsic MakeKFromPoly(uCC::Any, u_pol::Any) -> Any, Any, Any, Any, Any
  {Shared tail of MakeK: given uCC and its (already found, irreducible)
   minimal polynomial u_pol over ZZ, build the optimized field, ramification
   screen, and complex embedding.  Returns bl, K, v, conj, uCC.}

  CC := Parent(uCC);
  eps := 10^(-Precision(CC)/2);
  if Degree(u_pol) eq 1 then
    K := RationalsAsNumberField();
    v := RealPlaces(K)[1];
    return true, K, v, false, Parent(uCC)!1;
  end if;
  lc := LeadingCoefficient(u_pol);
  K0 := NumberField(u_pol);
  u0 := K0.1;
  K := NumberField(MinimalPolynomial(lc*u0));
  u := K.1/lc;
  ps, foobar := TrialDivision(Discriminant(K));
  if foobar ne 1 and not IsSquare(foobar) then
    return false, _, _, _, _;
  end if;

  if foobar eq 1 then
    vprintf Shimura : "  ...coefficient found, with ps = %o and foobar = 1\n", ps;
  else
    vprintf Shimura : "  ...coefficient found, with ps = %o and sqrt(foobar) = %o\n", ps, Round(Sqrt(CC!foobar));
  end if;
  vprintf Shimura : "  ...%o\n", K;
  vprint Shimura : "  ...Trying to optimize"; 
  
  // Kop, iotaop := OptimizedRepresentation(K : Ramification := [p[1] : p in ps]);
  Kop, iotaop := Polredbestabs(K);
  uop := iotaop(u);
  
  vprintf Shimura : "  ...successfully optimized\n  Kop = %o\n  now finding complex embedding\n", Kop;
  minv, vind := Min([Abs(uCC-Evaluate(uop,v : Precision := Precision(CC))) : v in InfinitePlaces(Kop)]);
  if minv gt eps then
    // Need complex conjugate
    minv, vind := Min([Abs(Conjugate(uCC)-Evaluate(uop,v : Precision := Precision(CC))) : v in InfinitePlaces(Kop)]);
    conj := true;
  else
    conj := false;
  end if;
  if minv gt eps then
    vprint Shimura : "  ...failed to match; got a polynomial but it apparently sux";
    return false, _, _, _, _;
  end if;
  vprint Shimura : "  ...quality of match", RealField(4)!minv;
  v := InfinitePlaces(Kop)[vind];
  // return true, Kop, v, conj, uop;
  return true, Kop, v, conj, uCC;
end intrinsic;

intrinsic MakeK(uCC::Any, m::Any) -> Any, Any, Any, Any, Any
  {MakeK!  What more to say?}

  if m eq 1 then
    vprint Shimura : "  ...m eq 1, so taking QQ";
    K := RationalsAsNumberField();
    v := RealPlaces(K)[1];
    return true, K, v, false, Parent(uCC)!1;
  end if;

  vprintf Shimura : "  ...Trying to MakeK with m = %o\n", m;

  u_pol := PowerRelation(uCC, m : Al := "LLL");
  if Degree(u_pol) ne m or not IsIrreducible(u_pol) then
    if Degree(u_pol) gt 1 then
      vprint Shimura : "  ...coefficient not degree m, looked like degree", [<Degree(c[1]),c[2]> : c in Factorization(u_pol)];
    end if;
    return false, _, _, _, _;
  end if;
  return MakeKFromPoly(uCC, u_pol);
end intrinsic;

intrinsic MakeKBatch(cfs::SeqEnum, m::RngIntElt) -> Any, Any, Any, Any, Any
  {Batched, certified replacement for the MakeK search loop, backed by the
   external C relation finder (Cext/makek_relfinder.c, FLINT fmpz_lll).  For
   every candidate coefficient in cfs it finds and certifies the true minimal
   polynomial of degree <= m in a single threaded pass, then runs the usual
   MakeK tail (ramification screen, Polredbestabs, embedding) on the best
   candidate: largest certified degree, earliest index breaking ties.

   Returns bl, K, v, conj, uCC.  bl = false means NO candidate certified any
   relation -- with the certification in the C tool that is strong evidence
   the working precision is insufficient (raise prec), as opposed to the
   legacy loop which cannot distinguish "no relation" from "not enough
   precision" and grinds through O(m * #cfs) LLL calls before failing.

   Requires MAKEK_RELFINDER_BIN to point at the built binary; threads via
   MAKEK_RELFINDER_THREADS.  File handoff mirrors the CArnoldi solver:
   TMPDIR-respecting, random-tagged names, plain-text output (parsed, never
   eval'd).}

  cbin := GetEnv("MAKEK_RELFINDER_BIN");
  require cbin ne "" : "MAKEK_RELFINDER_BIN is not set";
  CC := Parent(cfs[1]);
  precbits := Ceiling(Precision(CC)*3.3219280948873623);

  tmpdir := GetEnv("TMPDIR");
  if tmpdir eq "" then
    tmpdir := "/tmp";
  end if;
  tag := Sprintf("%o_%o_%o", Getpid(), Round(1000*Realtime()) mod 10^9, Random(10^15));
  infile := Sprintf("%o/makek_in_%o.txt", tmpdir, tag);
  outfile := Sprintf("%o/makek_out_%o.txt", tmpdir, tag);

  F := Open(infile, "w");
  Puts(F, Sprintf("%o %o %o", precbits, #cfs, m));
  for u in cfs do
    Puts(F, Sprintf("%o", Real(u)));
    Puts(F, Sprintf("%o", Imaginary(u)));
  end for;
  delete F;

  ret := System(Sprintf("%o %o %o", cbin, infile, outfile));
  require ret eq 0 : "external relation finder failed";

  // parse: FOUND <idx> <deg> <log10resid> <c_0> ... <c_deg> | NOPREC <idx>
  best_deg := 0; best_idx := 0; best_cfs := [];
  nnoprec := 0;
  done := false;
  for line in Split(Read(outfile), "\n") do
    parts := Split(line, " ");
    if #parts eq 0 then continue; end if;
    if parts[1] eq "RELFINDER_DONE" then
      done := true;
    elif parts[1] eq "NOPREC" then
      nnoprec +:= 1;
    elif parts[1] eq "FOUND" then
      idx := StringToInteger(parts[2]) + 1;  // C is 0-based
      deg := StringToInteger(parts[3]);
      if deg gt best_deg or (deg eq best_deg and best_deg gt 0 and idx lt best_idx) then
        best_deg := deg;
        best_idx := idx;
        best_cfs := [StringToInteger(parts[k]) : k in [5..5+deg]];
      end if;
    end if;
  end for;
  require done : "external relation finder output truncated";
  System(Sprintf("rm -f %o %o", infile, outfile));

  if best_deg eq 0 then
    vprint Shimura : "  ...MakeKBatch: no candidate certified at this precision";
    return false, _, _, _, _;
  end if;
  // Guard against the trivial-rational trap: normalized coefficient lists
  // contain exact constants (e.g. a leading 1) that certify at degree 1
  // regardless of seed quality.  Only accept K = QQ when EVERY candidate
  // certified; a degree-1 best alongside NOPREC candidates means the
  // interesting coefficients could not be certified -- report failure so
  // the caller raises precision instead of building a wrong map.
  if best_deg eq 1 and nnoprec gt 0 then
    vprintf Shimura : "  ...MakeKBatch: only trivial degree-1 certifications (%o candidates NOPREC) -- insufficient precision\n", nnoprec;
    return false, _, _, _, _;
  end if;
  vprintf Shimura : "  ...MakeKBatch: certified minimal polynomial of degree %o at coefficient %o\n", best_deg, best_idx;
  uCC := cfs[best_idx];
  if best_deg eq 1 then
    K := RationalsAsNumberField();
    v := RealPlaces(K)[1];
    return true, K, v, false, Parent(uCC)!1;
  end if;
  ZZx<xZ> := PolynomialRing(Integers());
  u_pol := ZZx ! best_cfs;
  return MakeKFromPoly(uCC, u_pol);
end intrinsic;

intrinsic TriangleK(Gamma::GrpPSL2Tri) -> Any, Any, Any
{}
  return Gamma`TriangleK, Gamma`TriangleKv, Gamma`TriangleKIsConjugated;
end intrinsic;

intrinsic TriangleK(Sk::SeqEnum[SeqEnum[RngSerPowElt]], Gamma::GrpPSL2Tri : m := 0) -> Any, Any, Any
{}
  CCw := Parent(Sk[1][1]);
  CC := BaseRing(CCw);
  eps := 10^(-Precision(CC)/2);

  Theta := TriangleTheta(Sk, Gamma);

  if m eq 0 then
    sigma := DefiningPermutation(Gamma);
    m := #PassportRepresentatives(sigma : Pointed := true);
  end if;
  if m eq 1 then
    Gamma`TriangleK := RationalsAsNumberField();
    Gamma`TriangleKv := RealPlaces(Gamma`TriangleK)[1];
    Gamma`TriangleKIsConjugated := false;
    Gamma`TriangleKNumericalGenerator := CC!1;
    return Gamma`TriangleK, Gamma`TriangleKv, Gamma`TriangleKIsConjugated, Gamma`TriangleKNumericalGenerator;
  end if;

  Skc := [];
  for f in Sk do
    s := Degree(LeadingTerm(f[1]));
    while Abs(Coefficient(f[1],s)) lt eps do
      s +:= 1;
    end while;
    fc := [Coefficient(f[1],n)/Theta^(n-s) : n in [0..Precision(Parent(f[1]))-1]];
    Append(~Skc, fc);
  end for;

  // Compute number field
  fc := Skc[1];
  n := 0;
  repeat
    n +:= 1;
    cn := fc[n];
    if m eq 1 then
      assert Abs(Im(cn)) lt eps;  // if rational, should be real!
      cn := Re(cn);
    end if;

    bl, K, v, conj := MakeK(cn, m);
  until bl;

  Gamma`TriangleK := K;
  Gamma`TriangleKv := v;
  Gamma`TriangleKIsConjugated := conj;
  Gamma`TriangleKNumericalGenerator := fc[n];

  return K, v, conj, fc[n];
end intrinsic;

intrinsic RecognizeSeries(Sk::SeqEnum[SeqEnum[RngSerPowElt]], Gamma::GrpPSL2Tri : KeepTheta := true, m := 0) -> Any
{}
  CCw := Parent(Sk[1][1]);
  CC := BaseRing(CCw);
  eps := 10^(-Precision(CC)/2);
  NN := Precision(CCw);

  Theta := TriangleTheta(Sk, Gamma);
  K, v, conj, uCC := TriangleK(Sk, Gamma : m := m);
  if m eq 0 then
    m := Degree(K);
  end if;

  ZK := Integers(K);
  ZKbCC := [Evaluate(b,v : Precision := Precision(CC)) : b in Basis(ZK)];
  if conj then
    ZKbCC := [Conjugate(zkb) : zkb in ZKbCC];
  end if;
  if not KeepTheta then
    // Adjust Theta
    Skc := [];
    for f in Sk do
      s := Degree(LeadingTerm(f[1]));
      while Abs(Coefficient(f[1],s)) lt eps do
        s +:= 1;
      end while;
      fc := [Coefficient(f[1],n)/Theta^(n-s) : n in [0..Precision(Parent(f[1]))-1]];
      Append(~Skc, fc);
    end for;

    kappapass := 0;
    repeat
      fb := [];
      for n := 0 to #fc-1 do
        if m eq 1 then
          lin := LinearRelation(ZKbCC cat [-fc[n+1]] cat [CC.1] : Al := "LLL");
          // ignore imaginary part   TODO: Check it in range
        else
          lin := LinearRelation(ZKbCC cat [-fc[n+1]] : Al := "LLL");
        end if;
        if lin[m+1] eq 0 then
          break;
        end if;
        Append(~fb, K!((ZK!lin[1..m])/lin[m+1]));  // no factorial here!
      end for;

      // only take first two recognized coefficients at first
      cntrec := [];
      n := 1;
      while fb[n] eq 0 do
        n +:= 1;
      end while;
      s := n-1;
      n +:= 1;
      while #cntrec lt 2 do
        if fb[n] ne 0 then
          Append(~cntrec, <n-1, fb[n]>);
        end if;
        n +:= 1;
      end while;
      a := DefiningABC(Gamma)[1];
      t := cntrec[2][1]-cntrec[1][1];
      toa := Gcd(t,a);
      cntrec[1][1] := (cntrec[1][1]-s) div toa;
      cntrec[2][1] := (cntrec[2][1]-s) div toa;

      if m eq 1 then
        bb1 := &*([1] cat [ pp[1]^(Floor(pp[2]/cntrec[1][1])) : pp in Factorization(Numerator(cntrec[1][2]))])*
               &*([1] cat [ pp[1]^(Floor(-pp[2]/cntrec[1][1])) : pp in Factorization(Denominator(cntrec[1][2]))]);
        bb2 := &*([1] cat [ pp[1]^(Floor(pp[2]/cntrec[2][1])) : pp in Factorization(Numerator(cntrec[2][2]))])*
               &*([1] cat [ pp[1]^(Floor(-pp[2]/cntrec[2][1])) : pp in Factorization(Denominator(cntrec[2][2]))]);
        beta := Gcd(Numerator(bb1),Numerator(bb2))/Lcm(Denominator(bb1),Denominator(bb2));
      else
        bb1 := &*([1*ZK] cat [ pp[1]^(Floor(pp[2]/cntrec[1][1])) : pp in Factorization(cntrec[1][2]*ZK)]);
        bb2 := &*([1*ZK] cat [ pp[1]^(Floor(pp[2]/cntrec[2][1])) : pp in Factorization(cntrec[2][2]*ZK)]);
        bb := bb1+bb2;
        ClK, mCl := ClassGroup(ZK);
        bb0 := mCl((bb^-1)@@mCl);
        bb *:= bb0;
        bl, beta := IsPrincipal(bb);
      end if;
      betaCC := Evaluate(beta, v : Precision := Precision(CC));
      Theta *:= betaCC^(1/toa);

      vprintf Shimura : "With beta = %o, now Theta = %o\n", beta, Theta;

      if t/Gcd(a,t) gt 1 and kappapass eq 0 then
        at := Lcm(a,t);
        _, kappa := TrianglePhi(Gamma);
        alphat := 1/(Theta*kappa)^at;
        if m eq 1 then
          lin := LinearRelation(ZKbCC cat [-alphat] cat [CC.1] : Al := "LLL");
        else
          lin := LinearRelation(ZKbCC cat [-alphat] : Al := "LLL");
        end if;
        alphat := (ZK!lin[1..m])/lin[m+1];
        if not IsPower(alphat, at div t) then
          Theta /:= (CC!Evaluate(alphat, v : Precision := Precision(CC)))^(1/(at div a));
        end if;

        vprintf Shimura : "Kappa adjustment, now Theta = %o\n", Theta;
        kappapass := 1;

        f := Sk[1];
        s := Degree(LeadingTerm(f[1]));
        while Abs(Coefficient(f[1],s)) lt eps do
          s +:= 1;
        end while;
        fc := [Factorial(n)*Coefficient(f[1],n)/Theta^(n-s) : n in [0..Precision(Parent(f[1]))-1]];
      else
        kappapass := 2;
      end if;
    until kappapass eq 2;

    Gamma`TriangleTheta := Theta;
  end if;

  Skc := [];
  for f in Sk do
    s := Degree(LeadingTerm(f[1]));
    while Abs(Coefficient(f[1],s)) lt eps do
      s +:= 1;
    end while;
    fc := [Coefficient(f[1],n)/Theta^(n-s) : n in [0..Precision(Parent(f[1]))-1]];
    Append(~Skc, fc);
  end for;

  Skb := RecognizeOverK(Skc, K, v, conj : escapeOK := true);

  KTw<Tw> := PowerSeriesRing(K, NN+1);
  Skb := [ KTw!fb + BigO(Tw^(#fb)) : fb in Skb];

  return Skb;
end intrinsic;

intrinsic RecognizeOverK(Skc::SeqEnum[SeqEnum[FldComElt]], K::FldAlg, v::PlcNumElt, conj::BoolElt : escapeOK := false) -> SeqEnum
{Recognizes a sequence of sequences as elements of K with respect to the embedding v, conjugated if conj.}

  CC := Parent(Skc[1][1]);
  eps := 10^(-Precision(CC)/2);

  ZK := Integers(K);
  ZKbCC := [CC!Evaluate(b,v : Precision := Precision(CC)) : b in Basis(ZK)];
  if conj then
    ZKbCC := [Conjugate(zkb) : zkb in ZKbCC];
  end if;

  m := Degree(K);

  if GetEnv("MAKEK_RELFINDER_BIN") ne "" and m gt 1 then
    return RecognizeOverKBatch(Skc, K, ZKbCC : escapeOK := escapeOK);
  end if;

  Skb := [];
  for fc in Skc do
    fb := [];
    prevden := 1;
    for n := 0 to #fc-1 do
      if m eq 1 then
        powrel := PowerRelation(-prevden*Re(fc[n+1]),1 : Al := "LLL");
        if Degree(powrel) lt 1 then 
          lin := [0,1];
        else
          lin := Eltseq(powrel);
        end if;
      else
        lin := LinearRelation(ZKbCC cat [-prevden*fc[n+1]] : Al := "LLL");
      end if;
      if lin[m+1] eq 0 then
        error "Failed to find linear relation in RecognizeOverK";
      end if;
      print "Denominator", lin[m+1], "should be not too large!";
      Append(~fb, K!((ZK!lin[1..m])/lin[m+1]/prevden));
      prevden *:= lin[m+1];
      fbv := CC!Evaluate(fb[#fb],v : Precision := Precision(CC));
      if conj then fbv := Conjugate(fbv); end if;
      err := Abs(fbv - fc[n+1]);
      vprintf Shimura : "Coefficient %o of %o in array %o recognized, error = %o \n", n+1, #fc, Index(Skc, fc),
        RealField(4)!err;
      if Abs(err) gt eps then
        if escapeOK then fb := fb[1..#fb-1]; break n;
        else error "Insufficient precision in RecognizeOverK, and no way to abort!  Increase precision"; end if;
      end if;
    end for;
    Append(~Skb, fb);
  end for;

  return Skb;
end intrinsic;

function OverKRunRelfinder(seqs, ZKbCC, m, precbits, cbin, tmpdir)
  // one --overk invocation on the given sequences; returns the found map
  tag := Sprintf("%o_%o_%o", Getpid(), Round(1000*Realtime()) mod 10^9, Random(10^15));
  infile := Sprintf("%o/overk_in_%o.txt", tmpdir, tag);
  outfile := Sprintf("%o/overk_out_%o.txt", tmpdir, tag);
  F := Open(infile, "w");
  Puts(F, Sprintf("%o %o %o", precbits, m, #seqs));
  for b in ZKbCC do
    Puts(F, Sprintf("%o", Real(b)));
    Puts(F, Sprintf("%o", Imaginary(b)));
  end for;
  for fc in seqs do
    Puts(F, Sprintf("%o", #fc));
    for c in fc do
      Puts(F, Sprintf("%o", Real(c)));
      Puts(F, Sprintf("%o", Imaginary(c)));
    end for;
  end for;
  delete F;
  ret := System(Sprintf("%o --overk %o %o", cbin, infile, outfile));
  error if ret ne 0, "external relation finder (--overk) failed";
  found := AssociativeArray();
  done := false;
  for line in Split(Read(outfile), "\n") do
    parts := Split(line, " ");
    if #parts eq 0 then continue; end if;
    if parts[1] eq "RELFINDER_DONE" then
      done := true;
    elif parts[1] eq "FOUND" or parts[1] eq "UNCERT" then
      if parts[1] eq "UNCERT" then
        vprintf Shimura : "  ...RecognizeOverK: coefficient %o/%o accepted UNCERTIFIED (marginal height for this precision)\n", parts[2], parts[3];
      end if;
      found[<StringToInteger(parts[2]) + 1, StringToInteger(parts[3]) + 1>] :=
        <StringToInteger(parts[4]), [StringToInteger(parts[k]) : k in [5..4+m]]>;
    end if;
  end for;
  error if not done, "external relation finder (--overk) output truncated";
  System(Sprintf("rm -f %o %o", infile, outfile));
  return found;
end function;

intrinsic RecognizeOverKBatch(Skc::SeqEnum, K::FldAlg, ZKbCC::SeqEnum : escapeOK := false) -> SeqEnum
  {Batched certified RecognizeOverK backed by the external C relation finder
   (Cext/makek_relfinder --overk).  Same semantics as the legacy loop --
   integral-basis coordinates, per-sequence denominator chaining, eps check
   -- but one threaded external pass over all sequences, and a certified
   NOPREC verdict on insufficient precision instead of hours of grinding
   before the same failure.}

  cbin := GetEnv("MAKEK_RELFINDER_BIN");
  require cbin ne "" : "MAKEK_RELFINDER_BIN is not set";
  CC := Parent(ZKbCC[1]);
  eps := 10^(-Precision(CC)/2);
  m := Degree(K);
  ZK := Integers(K);
  precbits := Ceiling(Precision(CC)*3.3219280948873623);

  tmpdir := GetEnv("TMPDIR");
  if tmpdir eq "" then
    tmpdir := "/tmp";
  end if;
  found := OverKRunRelfinder(Skc, ZKbCC, m, precbits, cbin, tmpdir);

  // Smooth-denominator rescale retry (the 17T7 trick, cf. Sam's
  // denom_recognition branch): denominators grow as powers of a smooth base
  // D along the coefficient sequences, and a sequence whose FIRST targets
  // already carry a high power cannot start its prevden chain.  Extract D
  // from every denominator recognized so far, probe D^j against the first
  // failed target of each truncated sequence (one threaded call over the
  // whole grid), and rerun the remainder of the sequence under the winning
  // scale.  Recognized scaled targets satisfy scale*c = a/den, so
  // c = a/(den*scale).
  scaleof := AssociativeArray();
  JMAX := 200;
  for sidx in [1..#Skc] do
    fc := Skc[sidx];
    k0 := 1;
    while k0 le #fc and IsDefined(found, <sidx, k0>) do k0 +:= 1; end while;
    if k0 gt #fc then continue; end if;
    dens := [ found[t][1] : t in Keys(found) ];
    if #dens eq 0 then continue; end if;
    // candidate bases: the collective smooth radical, plus the largest few
    // individual recognized denominators (a stuck sequence's scaling is
    // typically a power of ONE structured denominator, e.g. den(u), not of
    // the radical of everything)
    fac := TrialDivision(LCM(dens), 10^6);
    Drad := &*[ Integers() | f[1] : f in fac ];
    bigdens := Reverse(Sort(SetToSequence({ d : d in dens | d gt 1 })));
    cands := [ Integers() | ];
    for d in bigdens[1..Min(3, #bigdens)] cat [Drad] do
      if d gt 1 and d notin cands then Append(~cands, d); end if;
    end for;
    if #cands eq 0 then continue; end if;
    // one threaded probe over the whole (base, power) grid
    grid := [ Parent(<1,1>) | ];
    for ci in [1..#cands] do
      maxj := Min(JMAX, (Precision(CC) div 3) div Max(1, #IntegerToString(cands[ci])));
      for j in [1..maxj] do Append(~grid, <ci, j>); end for;
    end for;
    if #grid eq 0 then continue; end if;
    vprintf Shimura : "  ...RecognizeOverK: sequence %o stuck at %o; probing %o candidate scales from %o bases\n", sidx, k0, #grid, #cands;
    probe := OverKRunRelfinder([ [ CC!(cands[g[1]]^g[2]) * fc[k0] ] : g in grid ],
                               ZKbCC, m, precbits, cbin, tmpdir);
    scale := 0;
    best := 0;
    for gi in [1..#grid] do
      if IsDefined(probe, <gi, 1>) then
        s := cands[grid[gi][1]]^grid[gi][2];
        if scale eq 0 or s lt scale then scale := s; best := gi; end if;
      end if;
    end for;
    if scale eq 0 then continue; end if;
    vprintf Shimura : "  ...RecognizeOverK: scale %o^%o unlocks sequence %o; rerunning remainder\n", cands[grid[best][1]], grid[best][2], sidx;
    rerun := OverKRunRelfinder([ [ CC!scale * c : c in fc[k0..#fc] ] ],
                               ZKbCC, m, precbits, cbin, tmpdir);
    for n in [k0..#fc] do
      if IsDefined(rerun, <1, n - k0 + 1>) then
        found[<sidx, n>] := rerun[<1, n - k0 + 1>];
        scaleof[<sidx, n>] := scale;
      end if;
    end for;
  end for;

  Skb := [];
  for sidx in [1..#Skc] do
    fc := Skc[sidx];
    fb := [];
    for n in [1..#fc] do
      if not IsDefined(found, <sidx, n>) then
        if escapeOK then break; end if;
        error "Insufficient precision in RecognizeOverK (certified by the external relation finder); increase prec";
      end if;
      den, coords := Explode(found[<sidx, n>]);
      scdef, sc := IsDefined(scaleof, <sidx, n>);
      if not scdef then sc := 1; end if;
      elt := K!((ZK!coords)/(den*sc));
      // final eps check against the numerical value, via the embedded basis
      // (ZKbCC already encodes the place and conjugation)
      fbv := &+[ CC!coords[i]*ZKbCC[i] : i in [1..m] ] / (CC!den * CC!sc);
      err := Abs(fbv - fc[n]);
      vprintf Shimura : "Coefficient %o of %o in array %o recognized (batch), error = %o \n",
        n, #fc, sidx, RealField(4)!err;
      if err gt eps then
        if escapeOK then break; end if;
        error "RecognizeOverK batch result fails the eps check; increase prec";
      end if;
      Append(~fb, elt);
    end for;
    Append(~Skb, fb);
  end for;
  return Skb;
end intrinsic;

//why FldAlg instead of FldNum?
intrinsic RecognizeOverK(z::FldComElt, K::FldAlg, v::PlcNumElt, conj::BoolElt) -> Any
{Recognizes a complex number as an element of K with respect to the embedding v, conjugated if conj.}
  CC := Parent(z);
  ZK := Integers(K);
  ZKbCC := [CC!Evaluate(b,v : Precision := Precision(CC)) : b in Basis(ZK)];
  if conj then
    ZKbCC := [Conjugate(zkb) : zkb in ZKbCC];
  end if;
  m := Degree(K);

  if m eq 1 then
    lin := LinearRelation(ZKbCC cat [-Re(z)] : Al := "LLL");
  else
    lin := LinearRelation(ZKbCC cat [-z] : Al := "LLL");
  end if;
  z_K := (ZK!lin[1..m])/lin[m+1];
  z_K := K!z_K;

  return z_K;
end intrinsic;
